version: '3.2'

services:
  elasticsearch:
    image: blacktop/elasticsearch:7.10
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
  kibana:
    image: blacktop/kibana:7.10
    ports:
      - '5601:5601'
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
